FROM quay.io/toolbx-images/alpine-toolbox:3.21

# renovate: datasource=github-releases depName=tofuutils/tenv
ARG TENV_VERSION=v4.2.4

RUN wget -q https://github.com/tofuutils/tenv/releases/download/$TENV_VERSION/tenv_${TENV_VERSION}_amd64.apk && \
    apk add --no-cache \
    ansible \
    ansible-lint \
    python3 && \
    apk add --no-cache --allow-untrusted tenv_${TENV_VERSION}_amd64.apk && \
    tenv tofu install latest && \
    tenv terraform install latest
