name: "Alpine Linux: Build and push toolbx images"

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - alpine/**
      - .github/workflows/alpine.yaml
  push:
    branches:
      - main
    paths:
      - alpine/**
      - .github/workflows/alpine.yaml
  schedule:
    - cron:  '0 0 * * MON'


jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: alpine
          image: toolbox-iac-alpine
          tags: latest
          containerfiles: alpine/Containerfile
          layers: false
          oci: true

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          image: toolbox-iac-alpine
          registry: ghcr.io/${{ github.repository_owner }}
          tags: latest