name: trivy-scan
on:
  schedule: 
    - cron: "00 8 * * *" # scan at 8:00 UTC every day 

  workflow_run:
    workflows: ["Alpine Linux: Build and push toolbx images"] # Scan automatically after build
    types:
      - completed
    branches:
      - 'main'

  workflow_dispatch: # allow manually triggering builds

env:
  IMAGE_NAME: toolbox-iac-alpine
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  scan:
    name: Trivy
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
        with:
          image-ref: '${{ env.IMAGE_REGISTRY}}/${{ env.IMAGE_NAME }}:latest'
          format: template
          scanners: vuln,secret,misconfig
          template: '@/contrib/sarif.tpl'
          output: trivy-results-${{ env.IMAGE_NAME}}.sarif
          timeout: 30m0s
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        with:
          sarif_file: trivy-results-${{ env.IMAGE_NAME }}.sarif

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: Trivy scan SARIF upload
          path: trivy-results-${{ env.IMAGE_NAME }}.sarif